/** Full genre list, sorted alphabetically (A–Z). */
export const GENRES = [
  "Afrobeats",
  "Alternative R&B",
  "Alternative Rock",
  "Ambient",
  "Bedroom Pop",
  "Bluegrass",
  "Blues",
  "Bossa Nova",
  "Chillwave",
  "Classical",
  "Cloud Rap",
  "Country",
  "Dance Pop",
  "Dark Pop",
  "Deep House",
  "Drill",
  "drum and bass",
  "Dub",
  "EDM",
  "Electronic",
  "Emo",
  "Folk",
  "Funk",
  "Grime",
  "Grunge",
  "Hard Rock",
  "Heavy Metal",
  "Hip-Hop",
  "House",
  "Hyperpop",
  "Indie Folk",
  "Indie Pop",
  "Indie Rock",
  "Jazz",
  "K-Pop",
  "Latin Pop",
  "Lo-Fi",
  "Melodic Rap",
  "Metal",
  "Neo-Soul",
  "New Wave",
  "Noise Pop",
  "Nu-Jazz",
  "Orchestral",
  "Phonk",
  "Piano Ballad",
  "Pop",
  "Pop Punk",
  "Post-Rock",
  "Progressive Rock",
  "Punk",
  "R&B",
  "Rap",
  "Reggae",
  "Reggaeton",
  "Singer-Songwriter",
  "Ska",
  "Slow Burn Pop",
  "Soul",
  "Synthpop",
  "Tech House",
  "Techno",
  "Trap",
  "UK Garage",
  "Underground Hip-Hop",
  "World Music",
] as const;
